openapi: '3.0.0'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/PickleRick-sama/stock-tracker/1.0.0

info:
  description: This API represents the core StockTracker API. See info on verbs here https://restfulapi.net/http-methods/

  version: '1.0.0'
  title: Stock Tracker API
  contact:
    email: ifedayoadeniyi@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

##################################################
##### Tags in the system

tags:
  - name: Auth
    description: Endpoint for managing all the authentication going on in the system
    externalDocs:
      url: https://app.swaggerhub.com/apis-docs/PickleRick-sama/stock-tracker/1.0.0#/Auth

  - name: Users
    description: This endpoint provides information about a particular user
    externalDocs:
      url: https://app.swaggerhub.com/apis-docs/PickleRick-sama/stock-tracker/1.0.0#/Users

paths:
  #####################################
  ### Authentication

  /auth/signup:
    post:
      tags:
        - Auth
      summary: Creates a user account
      description: Creates a user account
      requestBody:
        description: description
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterInfo'

      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '409':
          description: A user with provided email or phone_number already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        default:
          description: An error occured
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
